# Generated by Django 4.1.5 on 2023-05-30 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodz', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='option',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('img', models.CharField(max_length=100)),
                ('link', models.CharField(max_length=100)),
            ],
        ),
    ]
