# Generated by Django 4.1.5 on 2023-05-30 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodz', '0002_option'),
    ]

    operations = [
        migrations.CreateModel(
            name='fb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('msg', models.CharField(max_length=100)),
                ('mail', models.EmailField(max_length=254)),
            ],
        ),
    ]
